In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler , OneHotEncoder , LabelEncoder
import pickle

In [2]:
data = pd.read_csv("Churn_Modelling.csv")
data.head()

   RowNumber  CustomerId  ...  EstimatedSalary  Exited
0          1    15634602  ...        101348.88       1
1          2    15647311  ...        112542.58       0
2          3    15619304  ...        113931.57       1
3          4    15701354  ...         93826.63       0
4          5    15737888  ...         79084.10       0

[5 rows x 14 columns]

In [3]:
### Preprocessing the data

data = data.drop(['RowNumber','CustomerId','Surname'],axis=1)

In [4]:
## Encode categorical variables

label_encoder_gender = LabelEncoder()
data['Gender'] = label_encoder_gender.fit_transform(data['Gender'])
data

      CreditScore Geography  ...  EstimatedSalary  Exited
0             619    France  ...        101348.88       1
1             608     Spain  ...        112542.58       0
2             502    France  ...        113931.57       1
3             699    France  ...         93826.63       0
4             850     Spain  ...         79084.10       0
...           ...       ...  ...              ...     ...
9995          771    France  ...         96270.64       0
9996          516    France  ...        101699.77       0
9997          709    France  ...         42085.58       1
9998          772   Germany  ...         92888.52       1
9999          792    France  ...         38190.78       0

[10000 rows x 11 columns]

In [8]:
### Onehot encode geography
onehot_encoder_geo = OneHotEncoder(handle_unknown='ignore')
geo_encoded = onehot_encoder_geo.fit_transform(data[['Geography']]).toarray()
geo_encoded_df = pd.DataFrame(geo_encoded, columns=onehot_encoder_geo.get_feature_names_out(['Geography']))
geo_encoded_df

      Geography_France  Geography_Germany  Geography_Spain
0                  1.0                0.0              0.0
1                  0.0                0.0              1.0
2                  1.0                0.0              0.0
3                  1.0                0.0              0.0
4                  0.0                0.0              1.0
...                ...                ...              ...
9995               1.0                0.0              0.0
9996               1.0                0.0              0.0
9997               1.0                0.0              0.0
9998               0.0                1.0              0.0
9999               1.0                0.0              0.0

[10000 rows x 3 columns]

In [9]:
## Combine one hot encoded columns with original data

data = pd.concat([data.drop('Geography' , axis=1) , geo_encoded_df] , axis=1)
data.head()

   CreditScore  Gender  ...  Geography_Germany  Geography_Spain
0          619       0  ...                0.0              0.0
1          608       0  ...                0.0              1.0
2          502       0  ...                0.0              0.0
3          699       0  ...                0.0              0.0
4          850       0  ...                0.0              1.0

[5 rows x 13 columns]

In [10]:
## Split the data into dependent features and target
x = data.drop('EstimatedSalary',axis=1)
y = data['EstimatedSalary']

In [11]:
### Split the data in training and testing sets
x_train , x_test , y_train , y_test = train_test_split(x,y,test_size=0.2 , random_state=42)

In [12]:
## Scale these features
scaler = StandardScaler()
x_train = scaler.fit_transform(x_train)
x_test = scaler.transform(x_test)

In [13]:
## Save the encoders and scalar 

with open('label_encoder_gender.pkl' , 'wb') as file:
    pickle.dump(label_encoder_gender , file)

with open('onehot_encoder_geo.pkl' , 'wb') as file:
    pickle.dump(onehot_encoder_geo , file)

with open('scaler.pkl' , 'wb') as file:
    pickle.dump(scaler , file)

### ANN Regression problem statement

In [14]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [15]:
## Build our ANN model

model = Sequential([
    Dense(64,activation='relu' , input_shape=(x_train.shape[1],)),  ## Hidden layer 1 connected with input layer it has 64 hidden neurons in it
    Dense(32 , activation='relu'), ## Hidden layer 2 with 32 hidden neurons
    Dense(1)  ## output layer
])

##Compile the model
model.compile(optimizer='adam',loss='mean_absolute_error',metrics=['mae'])

model.summary()

c:\Users\Samiksha\OneDrive\Desktop\Python-genAi\ANNProjectImplementation\venv\Lib\site-packages\keras\src\layers\core\dense.py:100: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 64)             │           832 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 2,945 (11.50 KB)

 Trainable params: 2,945 (11.50 KB)

 Non-trainable params: 0 (0.00 B)

In [16]:
### Setup the tensorboard

from tensorflow.keras.callbacks import EarlyStopping , TensorBoard
import datetime

log_dir = "regressionlogs/fit" + datetime.datetime.now().strftime("%Y%m%d-%H%M%S")
tensorflow_callback = TensorBoard(log_dir=log_dir , histogram_freq=1)

In [17]:
## Setup Early stopping

early_stopping_callback = EarlyStopping(monitor='val_loss' , patience=10 , restore_best_weights=True)

In [18]:
## Train the model

history = model.fit(
    x_train , y_train , validation_data = (x_test , y_test) , epochs=100,
    callbacks=[tensorflow_callback , early_stopping_callback]
)

Epoch 1/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 100380.8594 - mae: 100380.8594 - val_loss: 98534.1797 - val_mae: 98534.1797
Epoch 2/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 99698.9297 - mae: 99698.9297 - val_loss: 97145.1484 - val_mae: 97145.1484
Epoch 3/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 97264.3594 - mae: 97264.3594 - val_loss: 93552.9297 - val_mae: 93552.9297
Epoch 4/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 92441.7578 - mae: 92441.7578 - val_loss: 87516.9375 - val_mae: 87516.9375
Epoch 5/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 85353.5312 - mae: 85353.5312 - val_loss: 79565.8281 - val_mae: 79565.8281
Epoch 6/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 76748.5938 - mae: 76748.5938 - val_loss: 70925.0078 - val_mae: 70925.0078
Epoch 7/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 68062.7578 - mae: 68062.7578 - val_loss: 63136.4453 - val_mae: 63136.4453
Epoch 8/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 60775.4102 - mae: 60775.4102 - val_loss: 57253.2695 - val_mae: 57253.2695
Epoch 9/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 55733.7812 - mae: 55733.7812 - val_loss: 53569.8906 - val_mae: 53569.8906
Epoch 10/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 52811.2891 - mae: 52811.2891 - val_loss: 51742.3828 - val_mae: 51742.3828
Epoch 11/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 51355.4766 - mae: 51355.4766 - val_loss: 51002.9844 - val_mae: 51002.9844
Epoch 12/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 50712.2969 - mae: 50712.2969 - val_loss: 50759.9531 - val_mae: 50759.9531
Epoch 13/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 50434.7422 - mae: 50434.7422 - val_loss: 50672.3711 - val_mae: 50672.3711
Epoch 14/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 50295.3594 - mae: 50295.3594 - val_loss: 50626.9688 - val_mae: 50626.9688
Epoch 15/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 50210.1367 - mae: 50210.1367 - val_loss: 50592.6523 - val_mae: 50592.6523
Epoch 16/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 50145.9883 - mae: 50145.9883 - val_loss: 50560.5977 - val_mae: 50560.5977
Epoch 17/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 50093.1406 - mae: 50093.1406 - val_loss: 50528.7422 - val_mae: 50528.7422
Epoch 18/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 50049.1992 - mae: 50049.1992 - val_loss: 50501.6133 - val_mae: 50501.6133
Epoch 19/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 50011.8672 - mae: 50011.8672 - val_loss: 50474.9844 - val_mae: 50474.9844
Epoch 20/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49978.7344 - mae: 49978.7344 - val_loss: 50448.5586 - val_mae: 50448.5586
Epoch 21/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49948.5703 - mae: 49948.5703 - val_loss: 50427.5781 - val_mae: 50427.5781
Epoch 22/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49922.0938 - mae: 49922.0938 - val_loss: 50406.5859 - val_mae: 50406.5859
Epoch 23/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49896.9297 - mae: 49896.9297 - val_loss: 50389.1328 - val_mae: 50389.1328
Epoch 24/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49873.2070 - mae: 49873.2070 - val_loss: 50372.8594 - val_mae: 50372.8594
Epoch 25/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49850.3242 - mae: 49850.3242 - val_loss: 50357.6875 - val_mae: 50357.6875
Epoch 26/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49828.1367 - mae: 49828.1367 - val_loss: 50344.4258 - val_mae: 50344.4258
Epoch 27/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49807.9766 - mae: 49807.9766 - val_loss: 50331.9688 - val_mae: 50331.9688
Epoch 28/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49788.7305 - mae: 49788.7305 - val_loss: 50318.4609 - val_mae: 50318.4609
Epoch 29/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49770.6719 - mae: 49770.6719 - val_loss: 50305.7930 - val_mae: 50305.7930
Epoch 30/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49753.3008 - mae: 49753.3008 - val_loss: 50295.0977 - val_mae: 50295.0977
Epoch 31/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49736.9062 - mae: 49736.9062 - val_loss: 50285.5625 - val_mae: 50285.5625
Epoch 32/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49720.8086 - mae: 49720.8086 - val_loss: 50277.3359 - val_mae: 50277.3359
Epoch 33/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49704.8477 - mae: 49704.8477 - val_loss: 50271.1367 - val_mae: 50271.1367
Epoch 34/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49689.9453 - mae: 49689.9453 - val_loss: 50265.6055 - val_mae: 50265.6055
Epoch 35/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49676.0469 - mae: 49676.0469 - val_loss: 50261.5000 - val_mae: 50261.5000
Epoch 36/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49661.9023 - mae: 49661.9023 - val_loss: 50256.8672 - val_mae: 50256.8672
Epoch 37/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49648.8945 - mae: 49648.8945 - val_loss: 50250.2812 - val_mae: 50250.2812
Epoch 38/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49636.2344 - mae: 49636.2344 - val_loss: 50246.0234 - val_mae: 50246.0234
Epoch 39/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49624.1094 - mae: 49624.1094 - val_loss: 50240.9219 - val_mae: 50240.9219
Epoch 40/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49612.6992 - mae: 49612.6992 - val_loss: 50236.9570 - val_mae: 50236.9570
Epoch 41/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49601.9883 - mae: 49601.9883 - val_loss: 50234.7031 - val_mae: 50234.7031
Epoch 42/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49592.3008 - mae: 49592.3008 - val_loss: 50233.8477 - val_mae: 50233.8477
Epoch 43/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49582.8320 - mae: 49582.8320 - val_loss: 50234.4023 - val_mae: 50234.4023
Epoch 44/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49574.2227 - mae: 49574.2227 - val_loss: 50234.5742 - val_mae: 50234.5742
Epoch 45/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49565.9609 - mae: 49565.9609 - val_loss: 50235.5469 - val_mae: 50235.5469
Epoch 46/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49557.7734 - mae: 49557.7734 - val_loss: 50234.7383 - val_mae: 50234.7383
Epoch 47/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49549.7305 - mae: 49549.7305 - val_loss: 50234.1406 - val_mae: 50234.1406
Epoch 48/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49542.2617 - mae: 49542.2617 - val_loss: 50235.5938 - val_mae: 50235.5938
Epoch 49/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49534.9805 - mae: 49534.9805 - val_loss: 50235.6172 - val_mae: 50235.6172
Epoch 50/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49528.0547 - mae: 49528.0547 - val_loss: 50234.8320 - val_mae: 50234.8320
Epoch 51/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49521.0977 - mae: 49521.0977 - val_loss: 50237.1758 - val_mae: 50237.1758
Epoch 52/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49514.3516 - mae: 49514.3516 - val_loss: 50238.2109 - val_mae: 50238.2109

In [19]:
%load_ext tensorboard

In [23]:
%tensorboard --logdir regressionlogs/fit20261028-193910

Reusing TensorBoard on port 6007 (pid 65288), started 0:00:02 ago. (Use '!kill 65288' to kill it.)

In [24]:
## Evaluate the model on test data

test_loss , test_mae = model.evaluate(x_test,y_test)
print(f'Test MAE : {test_mae}')

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 50233.8477 - mae: 50233.8477
Test MAE : 50233.84765625

In [25]:
model.save('regression_model.h5')

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.